name: Build (and publish if version tagged)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  tags:
    - 'v*'
env:
  LINUX_RUNNER: ubuntu-22.04
  MIN_PYTHON_VERSION: '3.10'
jobs:
  build:
    strategy:
      matrix:
        os: [ $LINUX_RUNNER, windows-2022, macos-12 ]
        python-version: [ MIN_PYTHON_VERSION, '3.11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          pip install pytest
      - name: Test
        run: |
          pytest
      - name: Publish package
        if: startsWith(github.event.ref, 'refs/tags/v') && matrix.os == $LINUX_RUNNER && python-version == MIN_PYTHON_VERSION
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
