name: Build (and publish if version tagged)
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-12 ]
        python-version: [ '3.10', '3.11' ]
        include:
          - os: ubuntu-22.04
            python-version: '3.10'
            publish: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          pip install pytest
      - name: Test
        run: |
          pytest
      - name: Publish package
        if: startsWith(github.event.ref, 'refs/tags/v') && matrix.publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
