name: Build (and publish if version tagged)
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-22.04', 'windows-2022', 'macos-12' ]
        python: [ '3.10', '3.11' ]
        jre: [ '11', '17' ]
        include:
          - os: 'ubuntu-22.04'
            python: '3.10'
            jre: '11'
            publish: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jre }}
          java-package: 'jre'
          distribution: 'temurin'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .
          pip install pytest
      - name: Test
        run: |
          python -m pytest
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.event.ref, 'refs/tags/v') && matrix.publish
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
